// Material Design 3 Styling Tokens for MotoReady
export const theme = {
  light: {
    colors: {
      primary: '#FF5722',          // Moto Orange
      onPrimary: '#FFFFFF',
      primaryContainer: '#FFDBD0',
      onPrimaryContainer: '#3E0400',
      secondary: '#5E5F62',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#E8E2E0',
      onSecondaryContainer: '#1C1B1F',
      background: '#F2F4F5',
      onBackground: '#1C1B1B',
      surface: '#FFFFFF',
      onSurface: '#1C1B1B',
      surfaceVariant: '#F4E0DB',
      onSurfaceVariant: '#53433F',
      surfaceContainer: '#F3EDEB',
      surfaceContainerHigh: '#EAE2DF',
      surfaceContainerHighest: '#E2D9D6',
      outline: '#85736E',
      outlineVariant: '#D8C2BC',
      error: '#BA1A1A',
      onError: '#FFFFFF',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
      success: '#2E7D32',
      onSuccess: '#FFFFFF',
      successContainer: '#C8E6C9',
      onSuccessContainer: '#1B5E20',
      warning: '#F57C00',
      warningContainer: '#FFE0B2',
      onWarningContainer: '#E65100',
      info: '#0288D1',
      infoContainer: '#B3E5FC',
      onInfoContainer: '#01579B',
      cardGradient: ['#1A237E', '#311B92'], // Deep indigo/purple gradient
    },
    shadows: {
      level1: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 1,
      },
      level2: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 3,
      },
      level3: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 6,
      },
    }
  },
  dark: {
    colors: {
      primary: '#FFB5A0',
      onPrimary: '#5E1700',
      primaryContainer: '#872B0D',
      onPrimaryContainer: '#FFDBD0',
      secondary: '#CBC4C2',
      onSecondary: '#322F2E',
      secondaryContainer: '#494544',
      onSecondaryContainer: '#E6E1E0',
      background: '#141211',
      onBackground: '#E6E1E0',
      surface: '#201A18',
      onSurface: '#E6E1E0',
      surfaceVariant: '#53433F',
      onSurfaceVariant: '#D8C2BC',
      surfaceContainer: '#2D2321',
      surfaceContainerHigh: '#392E2B',
      surfaceContainerHighest: '#453935',
      outline: '#A08D89',
      outlineVariant: '#53433F',
      error: '#FFB4AB',
      onError: '#690005',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
      success: '#81C784',
      onSuccess: '#1B5E20',
      successContainer: '#2E7D32',
      onSuccessContainer: '#C8E6C9',
      warning: '#FFB74D',
      warningContainer: '#E65100',
      onWarningContainer: '#FFE0B2',
      info: '#4FC3F7',
      infoContainer: '#01579B',
      onInfoContainer: '#B3E5FC',
      cardGradient: ['#0D1137', '#1F1135'], // Dark Mode deep indigo/purple gradient
    },
    shadows: {
      level1: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
        elevation: 1,
      },
      level2: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.4,
        shadowRadius: 5,
        elevation: 4,
      },
      level3: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.5,
        shadowRadius: 10,
        elevation: 8,
      },
    }
  },
  shapes: {
    small: 8,
    medium: 12,
    large: 16,
    extraLarge: 28,
    full: 9999,
  },
  typography: {
    fontFamily: 'System, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    sizes: {
      eyebrow: 12,
      bodySmall: 13,
      bodyMedium: 14,
      bodyLarge: 16,
      titleSmall: 16,
      titleMedium: 18,
      titleLarge: 22,
      displaySmall: 24,
      displayMedium: 32,
      displayLarge: 44,
    }
  }
};
